
import java.util.ArrayList;
import java.util.Scanner;

public class Main {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        Library library = new Library();
        boolean running = true;
        while(running) {
            System.out.println("Library Management System");
            System.out.println("1. Add Book \n2. Remove Book \n3. Search Book by Title \n4. Search Book by Author \n5. Display All Books \n6. Display All Available Books \n7. Borrow Book \n8. Return Book \n9. Exit");
            System.out.println("Choose an option: ");
            int choice = scanner.nextInt();
            scanner.nextLine(); // Consume newline generated by nextInt()
            ArrayList<Book> foundBooks = new ArrayList<>();
            switch(choice) {
                case 1:
                    System.out.println("Enter Book ID: ");
                    int id = scanner.nextInt();
                    scanner.nextLine();
                    System.out.println("Enter Book Title: ");
                    String title = scanner.nextLine();
                    System.out.println("Enter Book Author: ");
                    String author = scanner.nextLine();
                    System.out.println("Enter Book Year: ");
                    int year = scanner.nextInt();
                    scanner.nextLine();
                    Book newBook = new Book(id, title, author, year);
                    library.addBook(newBook);
                    break;
                case 2:
                    System.out.println("Enter Book ID to remove: ");
                    int removeID = scanner.nextInt();
                    scanner.nextLine();
                    library.removeBook(removeID);
                    break;
                case 3:
                    System.out.println("Enter Book Title to search: ");
                    String searchTitle = scanner.nextLine();
                    foundBooks = library.searchBookByTitle(searchTitle);
                    if(foundBooks != null) {
                        for(Book book : foundBooks) {
                            System.out.println(book);
                        }
                    }
                    else {
                        System.out.println("Book with title " + searchTitle + " not found.");
                    }
                    break;
                case 4:
                    System.out.println("Enter Book Author to search: ");
                    String searchAuthor = scanner.nextLine();
                    foundBooks = library.searchByAuthor(searchAuthor);
                    if(foundBooks != null) {
                        for(Book book : foundBooks) {
                            System.out.println(book);
                        }
                    }
                    else {
                        System.out.println("Book with author " + searchAuthor + " not found.");
                    }
                    break;
                case 5:
                    library.displayAllBooks();
                    break;
                case 6:
                    library.displayAllAvailableBooks();
                    break;
                case 7:
                    System.out.println("Enter Book ID to borrow:");
                    int borrowID = scanner.nextInt();
                    scanner.nextLine();
                    library.borrowBook(borrowID);
                    break;
                case 8:
                    System.out.println("Enter Book ID to return: ");
                    int returnID = scanner.nextInt();
                    scanner.nextLine();
                    library.returnBook(returnID);
                    break;
                case 9:
                    running = false;
                    System.out.println("Exiting.");
                    break;
                default:
                    System.out.println("Invalid Choice. Please try again.");
            }
        }
        scanner.close();
    }
}
